name: custom-database-export

services:
  php:
    type: php:8.2
    via: nginx:1.27
  mariadb1011:
    type: mariadb:10.11
    portforward: 3600
    creds:
      user: lamp
      password: lamp
      database: database
  mysql84:
    type: mysql:8.4
    portforward: 3601
    creds:
      user: lamp
      password: lamp
      database: database
  phpmyadmin:
    type: phpmyadmin:5.2
    hosts:
      - mariadb1011
      - mysql84
tooling:
  custom-database-export:
    service: php
    cmd: ./bin/custom-database-export.php
