name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          coverage: "pcov"
          ini-values: "zend.assertions=1"

      - name: "Prepare project"
        run: |
          composer install

      - name: Install Box
        run: |
          wget \
            "https://github.com/humbug/box/releases/download/4.2.0/box.phar" \
            --quiet \
            -O ./box
          chmod +x ./box
          sudo mv ./box /usr/local/bin

      - name: Build Application PHAR
        run: |
          box validate || exit 1
          box compile  || exit 1
          mv bin/custom-database-export.phar custom-database-export.phar

      - name: Geting Tag Name
        id: get-version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}

      - uses: actions/upload-artifact@v3
        with:
          name: custom-database-export.phar
          path: ./custom-database-export.phar

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.get-version.outputs.version }}
          tag: ${{ steps.get-version.outputs.version }}
          body: 'Next stable release.'
          allowUpdates: true
          artifacts: custom-database-export.phar
          artifactContentType: application/x-php
