name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          coverage: "pcov"
          ini-values: "zend.assertions=1"

      - name: "Prepare project"
        run: |
          composer install

      - name: "Build phar"
        run: |
          wget -O phive.phar "https://phar.io/releases/phive.phar"
          chmod +x phive.phar
          phive.phar install humbug/box
          box build

      - name: 'Upload artifcats'
        uses: actions/upload-artifact@v3
        with:
          name: custom-database-export.phar
          path: bin/custom-database-export.phar
