name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          coverage: "pcov"
          ini-values: "zend.assertions=1"

      - name: "Prepare project"
        run: |
          composer install

      - name: "Install PHIVE"
        uses: szepeviktor/phive@v1
        with:
          home: "${{ runner.temp }}/.phive"
          binPath: "${{ github.workspace }}/tools/phive"

      - name: "Install PHP tools with PHIVE"
        uses: "szepeviktor/phive-install@v1"
        with:
          home: "${{ runner.temp }}/.phive"
          binPath: "${{ github.workspace }}/tools/phive"
          trustGpgKeys: "4AA394086372C20A,CF1A108D0E7AE720,E82B2FB314E9906E"
        run: phive install humbug/box

      - name: "Build phar"
        run: box build

      - name: 'Upload artifcats'
        uses: actions/upload-artifact@v3
        with:
          name: custom-database-export.phar
          path: bin/custom-database-export.phar
